# Generated by Django 4.1.3 on 2022-11-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMonSLIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sli_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueLabels',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'issue_labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuePriority',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'issue_priority',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=1440)),
                ('priority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_sla', to='base_app.issuepriority')),
            ],
            options={
                'db_table': 'issue_sla',
                'ordering': ['minutes'],
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=128, null=True)),
                ('project_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('assignee_display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status_name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=4068, null=True)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('creator_display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('labels', models.ManyToManyField(related_name='label_issue', to='base_app.issuelabels')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_issue', to='base_app.issuepriority')),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AppMonSLI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('query', models.CharField(max_length=1024)),
                ('threshold', models.FloatField(default=0.0)),
                ('expression', models.CharField(choices=[('<', '<'), ('>', '>'), ('=', '='), ('!=', '!='), ('<=', '<='), ('>=', '>=')], default='<', max_length=8)),
                ('is_threshold_breached', models.BooleanField(default=False)),
                ('data_points', models.ManyToManyField(blank=True, related_name='sli', to='base_app.appmonslidata')),
            ],
            options={
                'db_table': 'mon_sli',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('yellow', 'YELLOW'), ('green', 'GREEN'), ('red', 'RED')], default='green', max_length=8)),
                ('slis', models.ManyToManyField(blank=True, related_name='sli_app', to='base_app.appmonsli')),
            ],
            options={
                'db_table': 'app_mon',
                'ordering': ['name'],
            },
        ),
    ]
